name: Run Tests

on: 
  [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'  # Ensure compatibility with ipython >= 8.12.0,<8.13.0

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run unit tests
      - name: Run unit tests
        run: |
          python -m unittest discover  # Run all the tests in the repository
